server:
  port: 8080
  servlet:
    context-path: /bookverse

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/book_store"
    username: root
    password: nhung-d
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: quadeptrai8hIrNT3QZjFzSdzZ3YvFWhQyoV4HnOrMbcsrIKMgHMlVctgWscP2zi

